# Generated by Django 3.1.3 on 2020-11-23 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone_Num', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Welayat', models.CharField(choices=[('1', 'Balkan'), ('2', 'Ahal'), ('3', 'Mary'), ('4', 'Lebap'), ('5', 'Dashoguz')], max_length=1)),
                ('Etrap', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TehnikiUlaglar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Welayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welayat', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='YukUlaglar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hachan', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Yorute_Tehnikalar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tehnikiulaglar')),
                ('Yuk_Ulaglar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.yukulaglar')),
                ('niraShaher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nira_Shaher', to='core.city')),
                ('niraWelayat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nira_Welayat', to='core.welayat')),
                ('niredenShaher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nireden_Shaher', to='core.city')),
                ('niredenWelayat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nireden_Velayat', to='core.welayat')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('car_type', models.CharField(choices=[('1', 'Yuk Ulaglar'), ('2', 'Yorute Tehnikalar')], max_length=1)),
                ('Yorute_Tehnikalar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tehnikiulaglar')),
                ('Yuk_Ulaglar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.yukulaglar')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Shaher',
            field=models.ManyToManyField(blank=True, to='core.City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Welayat',
            field=models.ManyToManyField(blank=True, to='core.Welayat'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
